kind: Service
apiVersion: v1
metadata:
  name: ocp-metal-ui
  namespace: assisted-installer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      # nodePort: 31000
  selector:
    app: ocp-metal-ui
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ocp-metal-ui
  namespace: assisted-installer
data:
  nginx.conf: |
    server {
        listen 8080;
        server_name _;

        root /app;
        index index.html;

        location /api {
            proxy_pass __BM_INVENTORY_URL__;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        location /app {
            try_files $uri /index.html;
        }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocp-metal-ui
  namespace: assisted-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocp-metal-ui
  template:
    metadata:
      labels:
        app: ocp-metal-ui
    spec:
      containers:
        - name: ocp-metal-ui
          image: __IMAGE__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/bitnami/nginx/conf # mount nginx-conf volumn to /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: ocp-metal-ui # place ConfigMap `ocp-metal-ui` on /etc/nginx/conf.d
            items:
              - key: nginx.conf
                path: nginx.conf
      restartPolicy: Always
